### PR TITLE
commit from mamatha

### PR DESCRIPTION
**Pull request by MamathaRswamy**
This commit is consist of one data
[data.xlsx](https://github.com/vasuki21/FirstRepository/files/9663932/data.xlsx)
base library function,

### CODE REVIEW

**Comment by vasuki21** [comment]
in this why u have used thred.sleep at line 14

**Comment by MamathaRswamy** [comment]
That element was not working with the implicit wait statement.

**Comment by vasuki21** [comment]
Ok i will merge this

**Comment by MamathaRswamy** [comment]
Thank you sirrrr

**Pull request merged**
